-- ============================================================
-- TGVmax Radar — suivi d'évolution des places
-- À exécuter UNE FOIS dans : Supabase → SQL Editor → New query
-- ============================================================

create table if not exists public.route_snapshots (
  id bigint generated by default as identity primary key,
  route_from  text        not null,   -- libellé gare/ville de départ (ex. « PARIS (intramuros) »)
  route_to    text        not null,   -- libellé gare/ville d'arrivée
  for_date    date        not null,   -- date du voyage surveillée
  oui_count   int         not null,   -- trains directs réservables avec l'abonnement
  itins_count int         not null default 0, -- itinéraires à correspondances trouvés
  captured_at timestamptz not null default now()
);

-- Lecture publique (l'historique est vu par tous les visiteurs)
alter table public.route_snapshots enable row level security;
drop policy if exists "lecture publique" on public.route_snapshots;
create policy "lecture publique" on public.route_snapshots
  for select using (true);

-- Insertion anonyme (uniquement des instantanés ; aucune donnée personnelle)
drop policy if exists "insertion anonyme" on public.route_snapshots;
create policy "insertion anonyme" on public.route_snapshots
  for insert with check (true);

-- Accélère les requêtes du site
create index if not exists idx_snapshots_route
  on public.route_snapshots (route_from, route_to, for_date, captured_at);
